package application;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class MainSceneController {
	Gerencia gerenciar = new Gerencia();
    @FXML
    private Label labelOpcao;
	
    @FXML
    private TextArea mostrarOpcoes;

    @FXML
    private TextArea mostrarResultado;
	
	@FXML
	private TextField tfTitle1;
	
    @FXML
    private TextField tfTitle2;
    
    @FXML
    private TextField tfTitle3;

	
	// Event Listener on Button.onAction
	
	@FXML
	public void btnOkCliked(ActionEvent event ) {
		//TODO Autogenerated
		String login = tfTitle1.getText();
		String senha = tfTitle2.getText();
		mostrarResultado.setText("Brasil");
		mostrarOpcoes.setText("Brasil");
		
		verificar(login,senha);
		
		
	}
	
	void verificar(String login, String senha) {
		gerenciar.adicionaUsuario("admin", "admin123", Tipo.ADMIN);
		gerenciar.adicionaUsuario("user", "user123", Tipo.USUARIO);
		gerenciar.adicionaUsuario("visitant", "visitant123", Tipo.VISITANTE);
		Perfil autenticarUsuário = gerenciar.autenticarPerfil(login, senha);
		if (autenticarUsuário != null) {
			mostrarResultado.setText("Autenticação bem sucedida! Perfil: " + autenticarUsuário.getTipo());
			String dadosToSing = login;
			switch (autenticarUsuário.getTipo()) {
			case ADMIN:
				System.out.println("Bem vindo, administrador. Você tem a opção de cadastrar e listar os usuários");
//				admin(dadosToSing);	
				break;
			case USUARIO:
				System.out.println("Bem vindo, usuário. Você irá receber a lista de usuários, participantes, que são usuários junto com você");
				gerenciar.getArrayPerfil();
				break;
			case VISITANTE:
				System.out.println("Bem vindo, visitante");
				break;
					
			}
		}
		else {
			System.out.println("Falha na autenticação. Usuario ou senha incorretos!");
		}
		
	}
}

//	private void admin(String dadosToSing) {
//		try {
//			
//			byte[] signature = gerenciar.entrarDados(dadosToSing, gerenciar.getKeyPair().getPrivate());
//			if(gerenciar.verificarAssinatura(dadosToSing, signature, gerenciar.getKeyPair().getPublic())) {
//				mostrarResultado.setText("Assinatura válida.");
//				String respostaInput;
//				do {
//				mostrarOpcoes.setText("Você deseja 1 - cadastrar novos usuários ou 2 - listar os usuários? ");
//				respostaInput = tfTitle3.getText();
//				
//				switch (respostaInput) {
//				case "1":
//					System.out.println("Digite o nome do usuário ");
//					String usernameInputNew = scanner.next();
//					
//					System.out.println("Digite a senha ");
//					String passwordInputNew =  scanner.next();
//					
//					gerenciar.adicionaUsuario(usernameInputNew, passwordInputNew, Tipo.USUARIO);
//					break;
//				case "2":
//					gerenciar.getArrayPerfil();
//				
//				default:
//					System.out.println("Obrigado por usar nossos serviços");
//				}
//				
//				}while(respostaInput == 1);
//				
//				
//			}
//			else {
//				System.out.println("Assinatura inválida");
//			}
//			
//			
//		}catch (Exception e) {
//			e.printStackTrace();
//		}
//	}
//
//}
